<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net7.0;net6.0;netstandard2.1;net48</TargetFrameworks>
    <Nullable>enable</Nullable>
    <IsTrimmable>True</IsTrimmable>
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisMode>All</AnalysisMode>
  </PropertyGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <Compile Include="..\shared\CodeAnalysis\**" />
  </ItemGroup>
  <ItemGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net6.0'))">
    <Compile Include="..\shared\CompilerServices\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\shared\Check.cs" />
  </ItemGroup>
</Project>
